### ISSUE TITLE
Skip other types of files

### ISSUE THREAD

**Issue by WangGithub0** [kliu57/go-go-web#2]
When i input a folder path, could you use Warning for other types of files, and add file name?
<img width="314" alt="image" src="https://github.com/kliu57/go-go-web/assets/20795443/91d1d35a-1bf7-403a-a84d-3a642298b53e">

**Comment by kliu57** [comment]
![issue2_fix](https://github.com/kliu57/go-go-web/assets/98062538/cd9d7bc5-2de3-44d3-a8d0-aa7b0415ba85)
Added input and output files names to success and error messages
