### ISSUE TITLE
Create unit test for testing markdown_to_html function

### ISSUE THREAD

**Issue by kliu57** [kliu57/go-go-web#24]
Create a unit test for the following function `src/convert.py` `def markdown_to_html(path, output_folder, css_url)`

This function takes an input md file path and writes to a new .html file

Please create a temporary input file to test the following:

```
# Replace *italic* and _italic_ with <em>italic</em>
# Replace **bold** and __bold__ with <strong>bold</strong>
# Replace `text` with <code>text</code>
# Replace multi-line code blocks that are inside ```...``` with <pre>...</pre>
```

**parameters of `markdown_to_html`:**

`path`: the path to an input file (ex: "examples/test3.md")
(create a temporary file using: `helpers.new_file(tmpdir, "your_file_name.md", pytest.your_global_var)`)

set `pytest.your_global_var` in `conftest.py` `pytest_configure()` to a long string which represents the markdown content of the input file (see other global variables in `conftest.py` to get an idea)

`output_folder`: the path for the output file (ex: til) (you can use a temporary directory, just put `tmpdir`)

`css_url`: no need to test this param, just use empty string

---

**Create the unit test** in `tests/convert_test.py`

**To name the unit test**, use `def test_markdown_to_html(tmpdir, helpers):`

**How to compare the output** of `markdown_to_html after running the function`:

```
    # Compare actual output file contents to expected
    output_path = tmpdir.join('your_file_name.html')
    assert helpers.file_contents(output_path) == pytest.your_html_global_var
```

you must set `pytest.your_html_global_var` in `conftest.py` `pytest_configure()` to a long string which represents the expected html content.

Please run pylint and autopep8 prior to submitting the pull request. (Instructions in [contributing.md](https://github.com/kliu57/go-go-web/blob/main/CONTRIBUTING.md))

**Comment by rjwignar** [comment]
I'd like to work on this issue.
