### ISSUE TITLE
Warning on output_file.write

### ISSUE THREAD

**Issue by WangGithub0** [kliu57/go-go-web#4]
<img width="845" alt="image" src="https://github.com/kliu57/go-go-web/assets/20795443/8e619e99-dbb9-4331-897e-bafa9fe25906">

**Comment by kliu57** [comment]
![issue4_fix](https://github.com/kliu57/go-go-web/assets/98062538/4682e6e1-284c-4060-8486-1d2f6cab08f2)
fixed pylint problem by specifying encoding when opening file
