### ISSUE TITLE
missing explicitly specifying coding

### ISSUE THREAD

**Issue by WangGithub0** [kliu57/go-go-web#5]
<img width="811" alt="image" src="https://github.com/kliu57/go-go-web/assets/20795443/52ea6e5f-60a7-4c2f-81c9-6176c59eaba7">

**Comment by kliu57** [comment]
![issue5_fix](https://github.com/kliu57/go-go-web/assets/98062538/4d2df15b-9c88-4717-a811-8724aa112c72)
specified encoding when using open
